name: Release

on:
  push:
    branches: [main, master]

permissions:
  contents: write
  pull-requests: write
  id-token: write
  attestations: write

jobs:
  release:
    name: Conventional Commit Release
    runs-on: ubuntu-latest

    steps:
      - name: Harden the runner
        uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Cocogitto Release
        uses: cocogitto/cocogitto-action@52d0023b4396897f1815648e553db2ab8d782f3a # v4.2.0
        with:
          release: true
          git-user: "github-actions[bot]"
          git-user-email: "github-actions[bot]@users.noreply.github.com"
